### ISSUE TITLE
Implement timeline update controls

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#284]
Touch screen:
pull latest events on touch screen pull down

Implement best UX practices for auto update on mobile and desktop.

**Comment by AyngUXUI** [comment]
Hi @ivelin - I'm happy to jump on this task.

**Comment by ivelin** [comment]
@AyngUXUI Great! Its assigned to you now.

**Comment by ivelin** [comment]
When you are finished, please tag @BKristenssonAlfsson and @sniperadmin for a peer review. Thank you!

**Comment by ivelin** [comment]
Also please tag @mchapman67 and @jjsenay to test the feature when the PR is merged.

**Comment by AyngUXUI** [comment]
Hi everyone. I'm sorry for the delay. I moved a few weeks ago and have been having major issues. I'm going to have to turn this assignment back over until my internet and laptops are back up and running.

**Comment by ivelin** [comment]
Done. Timeline view auto updates now.
