### ISSUE TITLE
Show UI PWA and Edge versions info in UI About page

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#299]

**Comment by ivelin** [comment]
It will make it easier to debug user issues with the UI.
Edge version info can also be displayed to aid in debugging edge related issue.

**Comment by peterminea** [comment]
Hello Ivelin!
How can we grab a task? This one looks interesting, as well as the "Introduce follow-actions for events" task.

**Comment by ivelin** [comment]
Hi @peterminea . Happy to see you jumping in. I just sent you a team invite and assigned this task to you. Once we close it, you can grab the follow-up actions issue next. 

Looking forward to your PR!

**Comment by ivelin** [comment]
@peterminea just to clarify. We already show the UI version in the About and Settings page. What's left to do is to show the connected Ambianic Edge version.

**Comment by ivelin** [comment]
BTW, keep in mind that we may start work soon on UI support for multiple connected Ambianic Edge devices. Just something to think about in the design and implementation of this issue.
