### ISSUE TITLE
Add timeline icon in app bar

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#302]
Display a timeline button in the main nav bar. Currently users have to open the top level menu and select the timeline option.  It would be convenient to have a way to go straight to the timeline from the navbar since its the most commonly visited page.

**Comment by AyngUXUI** [comment]
I can develop the timeline icon @ivelin

**Comment by ivelin** [comment]
@AyngUXUI Awesome. It's yours!

**Comment by AyngUXUI** [comment]
Hi everyone. I'm sorry for the delay. I moved a few weeks ago and have been having major issues. I'm going to have to turn this assignment back over until my internet and laptops are back up and running.
