### ISSUE TITLE
Add full integration test suite to cypress CI

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#326]
Currently cypress CI only tests UI components.

We need a full integration test suite, which:
- starts ambianic-edge in a CI docker space
- starts ambianic-pnp in a CI docker space
- starts and tests extensively ambianic-ui against the full simulated environment

The full integration test suite should trigger on UI release as well as once a week to make sure that any updates to dependencies are not breaking the user experience.

**Comment by sniperadmin** [comment]
🔥 the fire begins! 🔥

**Comment by ivelin** [comment]
done
