### ISSUE TITLE
UI to Edge pairing over remote network: Enable users at home to share edge Peer ID with remote family members who do not have access to the local Edge device network

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#327]
This use cases came up during a COVID19 hackathon:
https://devpost.com/software/remote-elderly-home-care-via-privacy-preserving-surveillance-dano89

Since during isolation, it is not possible to physically visit a home to pair UI with edge, we need a way for users at home to share connection with a remote user.

One way to achieve this is to allow in the UI manual entry of Edge ID. Instead of auto-pairing, which is not possible for remote users, the local home user can copy the ID from their UI and send it via email, sms or a messaging app to their remote family member. Then the remote user would manually paste the edge ID and connect to it. 

An even better UX could be to add a share button in the UI that sends a link to the remote user. Something like:
ui.ambianic.ai/connect?edge-id=12345

Once the remote user receives and clicks on the link, the UI will process it and begin connecting to the edge ID.

Open to ideas for an even smoother way to resolve this remote sharing scenario.

**Comment by ivelin** [comment]
![Screen Shot 2020-04-14 at 12 09 52 PM](https://user-images.githubusercontent.com/2234901/79254495-6c6d3f00-7e4a-11ea-9e72-8e68c3cf8552.png)

**Comment by ivelin** [comment]
![Screen Shot 2020-04-14 at 12 09 52 PM](https://user-images.githubusercontent.com/2234901/79254684-b6562500-7e4a-11ea-8991-03da2440f15b.png)

**Comment by ivelin** [comment]
Looks like there is Web Sharing API available for PWA that we can use to offer mobile native like sharing:
https://web.dev/web-share/

**Comment by ivelin** [comment]
On the receiving end, the UI could use the Web Share Target API to trigger remote Edge registration when the user mobile device receives a link shared by the home/Edge user:
https://web.dev/web-share-target/

**Comment by BKristenssonAlfsson** [comment]
That is only working Chrome right now. Perhaps a better solution would be a button that would copy the Edge ID to the systems clipboard and then the user could pass that on through SMS / Whatsapp or mail?

**Comment by ivelin** [comment]
I just experienced web sharing of a dev.to post that feels exactly like a native mobile app. It works fine on my old iPhone 6+. See screenshots and try for yourself to confirm.

**Comment by ivelin** [comment]
First iteration implemented and documented by @BKristenssonAlfsson :
https://docs.ambianic.ai/users/edge-pairing/

BTW, @BKristenssonAlfsson , it seems like the images broke in the doc above. Can you please take a look.
