### ISSUE TITLE
Visually protect Edge ID as a secret field

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#328]
Currently the Edge ID is always exposed visually in the UI Connect page.

Since it is a sensitive secret identifier, we should display it with a password obfuscation element and allow the user to explicitly show it (with the typical eye icon on the right side of a password field.)

**Comment by ivelin** [comment]
![Screen Shot 2020-04-14 at 12 09 52 PM](https://user-images.githubusercontent.com/2234901/79254922-164ccb80-7e4b-11ea-836c-4d5fee38ad73.png)

**Comment by Beardless-sheik** [comment]
Hey, anybody on this?

**Comment by ivelin** [comment]
> Hey, anybody on this?

Not yet. Go for it!
