### ISSUE TITLE
Display Edge Version in UI PWA

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#343]
It would be useful for debugging and information to quickly check in the UI the version of the connected Ambianic Edge install.

The edge can expose a Rest endpoint that shares version and other vital metrics essential to diagnosing and solving common problems.

**Comment by ivelin** [comment]
This issue is now implemented. Edge Peer ID is visible in Settings. Needs test coverage.

**Comment by ivelin** [comment]
Currently the settings page is confusing. It shows version info, but it is not clear whether that's the edge device version or the UI app version. See screenshot.

![IMG_5447](https://user-images.githubusercontent.com/2234901/106843101-dcafb000-666a-11eb-91ff-22c9c89f23e2.png)

**Comment by ivelin** [comment]
@vickywane looking at the edge code, it doesn't seem like we have a version API yet.

There is a [status API ](https://github.com/ambianic/ambianic-edge/blob/5c6da662aaf10dde91d0925d811758625283a02f/src/ambianic/webapp/flaskr.py#L155)on the edge, that currently provides minimal information to indicate that the edge module is in a good state. 

There is also a[ "/" API](https://github.com/ambianic/ambianic-edge/blob/5c6da662aaf10dde91d0925d811758625283a02f/src/ambianic/webapp/flaskr.py#L138) that returns basic edge information. 

We can enhance one of these to include edge version info. Or we can add a specific "/version" API.

Thoughts?

**Comment by vickywane** [comment]
@ivelin 

The object returned from the  `get_status` endpoint can be expanded to return a set version. 
Would you like this version to be fetched && displayed in the app?

**Comment by ivelin** [comment]
> @ivelin
> 
> The object returned from the `get_status` endpoint can be expanded to return a set version.
> Would you like this version to be fetched && displayed in the app?

Yes, that works. We can return status as a json structure with a version attribute. 

It looks like we need to do a few changes on the edge side to single source version number for packaging and runtime use.
It is currently stored in [setup.cfg](https://github.com/ambianic/ambianic-edge/blob/master/src/setup.cfg#L3). Set dynamically on each release by this [semantic release script](https://github.com/ambianic/ambianic-edge/blob/5c6da662aaf10dde91d0925d811758625283a02f/build/prepare-semantic-release.sh#L19). 

This is fine for packaging, but not simple for runtime lookup.

We can use the following single sourcing method.

Store the semantic version in a separate file, e.g. the main package [__init__.py](https://github.com/ambianic/ambianic-edge/blob/master/src/__init__.py) then reference it in setup.cfg via

```
[metadata]
version = attr: ambianic.__version__
```

as [documented here](https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-version).

This will make the edge package version easily accessible in the REST API code via 

```
ambianic.__version__
```

Thoughts?

**Comment by vickywane** [comment]
@ Looks like an ideal

**Comment by ivelin** [comment]
Cool, go for it!
