### ISSUE TITLE
Move p2p & pnp code to ServiceWorker

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#360]
Something I thought about but didn’t get around to doing was to move p2p to ServiceWorker. That way the vue app code is 100% vanilla blueprint. It can use regular web fetch for backend resources that ServiceWorker intercepts and funnel over webrtc. We currently have the pnp.fetch abstraction so its 80% there. It now needs to be moved to Service Worker and tested thoroughly.

@Bjorn continues to find new edge cases for p2p/pnp, which tells me that code really needs to be in its own capsule with minimal contracts to the rest of the PWA.

**Comment by bjorn** [comment]
You must mean another "@bjorn". :-)

**Comment by ivelin** [comment]
Apologies, I meant to tag @BKristenssonAlfsson
