### ISSUE TITLE
Move network intensive timeline fetch logic to WebWorker

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#361]
Related to #360

Another area I haven’t been able to get to but we may discuss is moving the logic for fetching timeline event data and images in the background to WebWorker. That might make the UI more responsive since the network intensive operations will be in a separate webworker thread. But this can be tested as a step after p2p is abstracted in ServiceWorker. That way the WebWorker thread can use plain fetch and feed results to the UI components on demand.
Just speculating. We won’t know until this is all coded and tested.

**Comment by BKristenssonAlfsson** [comment]
With the upcoming bluetooth implementation, we will need to get the webworker implemented so the PWA can wait with connecting to Edge until the setup has been done.

**Comment by ivelin** [comment]
I think this issue was opened before I had a good understanding about the purpose of WebWorker vs ServiceWorker.
In essence, WebWorker is a separate background thread that improves the UX responsiveness of the main app thread.
ServiceWorker is a proxy that allows the app to function offline as well as online.

WebWorker would be good for something like pre-loading and local cache of timeline events before the user scrolls down to see them.

ServiceWorker is the type of abstraction we can use to implement a smart proxy that "hides" the webrtc and BLE complexity behind a simple html5 fetch. With a well designed caching strategy in ServiceWorker, the PWA can be used to see past timeline events even if its offline. What I am not sure however is whether WebRTC and BLE APIs are available in a ServiceWorker sandbox. Needs to be verified.

Back to your original concern:
In order for the webrtc p2p connectivity to wait on BLE (if necessary) we need to extend the state machine logic in Vuex. That would be the most critical part. Once that works, we can optimize UX further by moving some of the online/offline transition to the ServiceWorker code. In theory the app logic shouldn't have to worry whether the UI is online of offline - it should just get valid responses through the basic html5 `fetch` API, which the ServiceWorker intercepts and adds magic to in the background. 

Hope that makes sense. Diving into the implementation will surely reveal more underwater rocks that I am not seeing yet.
