### ISSUE TITLE
Fix disabled assertions from lhci test config

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#377]
Currently we pass lhci at recommended level, except several assertions that need to be addressed:
        "font-display": "off",
        "unused-css-rules": "off",
        "uses-rel-preconnect": "off",

The following one should be allowed for pre-deployment tests, since we don't want test deployments to be indexed by search engines.
        "is-crawlable": "off"

See the config files here:
https://github.com/ambianic/ambianic-ui/tree/master/.github/lighthouse

**Comment by vickywane** [comment]
Is this about adding `"is-crawlable": "off"` to the `json` file ?

**Comment by ivelin** [comment]
No. "is-crawlable": "off" should be left `off` as is explained in the original comment.

More importantly we need to enable the other assertions in the list. For whatever reasons they failed at the time this issue was originally created.
