### ISSUE TITLE
Full Install via UI PWA - Improved app install flow

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#380]
Based on user feedback, we are revisiting the app install flow.
[New state diagram](https://app.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Ambianic.ai%20Install%20Flow#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D14LJfaOkwoWU_HZgIsVgqUuX2g9-9Nk8l%26export%3Ddownload)

[New UI flow mockup](https://app.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&page-id=igIhIKNUZmc0qu4BMqyh&title=Ambianic.ai%20Install%20Flow#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D14LJfaOkwoWU_HZgIsVgqUuX2g9-9Nk8l%26export%3Ddownload)

[Diagram source](https://app.diagrams.net/#G14LJfaOkwoWU_HZgIsVgqUuX2g9-9Nk8l)

**Comment by vickywane** [comment]
@ivelin i spent some time trying to understand the diagrams. If this is still an active issue, i would like to take a dive at it

**Comment by ivelin** [comment]
Yes, it is still an active topic of discussion. Thank you for taking interest in it.
Before diving into code, I would suggest catching up with @BKristenssonAlfsson 's work on BLE auto-discovery (#397).

**Comment by ivelin** [comment]
We now have a [simpler way to install](https://docs.ambianic.ai/users/quickstart/) Ambianic from scratch. It's time to embed setup instructions in the [UI flow](https://ui.ambianic.ai/), so that there is a single entry point for new users.

First time visitors to the UI PWA should be greeted and walked step-by-step through the setup process. Repeat visitors should be taken directly to their latest timeline, but be able to go to Settings for installing more devices and changing configuration settings on existing devices.

**Comment by vickywane** [comment]
This user onboarding plan seems awesome. If a little bug bounty is attached to it ( to reward the time spent working on this), I would love to implement it.

**Comment by ivelin** [comment]
@vickywane this is a possibility. [Here is the bounty](https://www.bountysource.com/issues/92600386-improve-app-install-flow?show_profile_modal=1). Feel free to update with your ask.

**Comment by ivelin** [comment]
@vickywane  Installed tipit.io for this repo if that works better for you. https://tipit.io/help 

```
.tip @user 1 TOKENCommand must be executed from a Github issue, will tip mentioned user 1 TOKEN.

.pool 1 TOKENWill create, or add to an existing bounty pool reward for the pull request that is linked and merged to solve the issue.
```

**Comment by ivelin** [comment]
boss.dev is now also available for bounties on ambianic repos. It has ability to ask for a bounty amount to close an issue:
https://www.boss.dev/doc/get-started

```
Bounty Earner Command Examples
/boss ask $100 | Announce you will close this issue for $100. In the near future, we will let you know when this number has been reached by one or more bounty creators.
/boss champion | Announce that you are working on the issue. It is still up to the repo owners whether or not to accept and merge your PR. And there may be multiple champions per issue.
/boss onit | alias for champion
/boss volunteer | alias for champion

```

**Comment by vickywane** [comment]
Alright. 

I would get working on this. Is there a target timeframe attached to this task?

**Comment by vickywane** [comment]
@ivelin I'd like to ask for $100. 

I went through the linked sketches on Draw.io. I guess the entire onboarding can take place in a single-center aligned modal or are there actual UI design mockups to complement the sketches?

**Comment by ivelin** [comment]
@vickywane I think you need to insert a boss command as an issue comment. That's how I contributed $50 to the bounty. Seems to work. See docs and examples:
https://www.boss.dev/doc/get-started
```
Bounty Earner Command Examples
/boss ask $100 | Announce you will close this issue for $100. In the near future, we will let you know when this number has been reached by one or more bounty creators.
/boss champion | Announce that you are working on the issue. It is still up to the repo owners whether or not to accept and merge your PR. And there may be multiple champions per issue.
/boss onit | alias for champion
/boss volunteer | alias for champion
```

**Comment by vickywane** [comment]
@ivelin I just tried following the examples

**Comment by ivelin** [comment]
> @ivelin I'd like to ask for $100.
> 
> I went through the linked sketches on Draw.io. I guess the entire onboarding can take place in a single-center aligned modal or are there actual UI design mockups to complement the sketches?

There is also [this mockup flow diagram](https://app.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&page-id=igIhIKNUZmc0qu4BMqyh&title=Ambianic.ai%20Install%20Flow#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D14LJfaOkwoWU_HZgIsVgqUuX2g9-9Nk8l%26export%3Ddownload). It was linked under the state diagram in the original issue.

[Vuetify stepper](https://vuetifyjs.com/en/components/steppers/) seems like a natural choice for the UX here, which we already use for the peer connection page but we can look at other ideas if you wish to propose.

**Comment by vickywane** [comment]
Great! 

Vue-stepper is a great choice, however, I am trying to visualize how it would be with the number of steps in the sketch.

**Comment by vickywane** [comment]
We can schedule a video call if you would like to explain the flow better

**Comment by ivelin** [comment]
Sounds good. Join the slack channel
<https://ambianicai.slack.com/archives/C011EADFSH2> to coordinate.

**Comment by ivelin** [comment]
It was nice speaking with you. Looking forward to seeing your work.

**Comment by ivelin** [comment]
@vickywane :

> Following the app installation flow, looking at the diagram where the requester ( the new user ) gets the shared connection link from an existing user, I can see the sketch continues the discussion in some sort of chat UI.
> Is there a messaging channel to handle this?
> To make it more clearer, how do we handle the installation after a user has received the shared access? @Bjorn @ivelin

If I understand the question correctly, there is no need for a separate channel. Once the requester receives the URL with the information about the edge device, they just need to click on the link and it will open directly the page of the Ambianic UI that handles remote connection to a new remote Peer. Currently [this is the section of the Settings page](https://github.com/ambianic/ambianic-ui/blob/3d5f60dc243a2a7fee840a57210e432ca6ff54f2/src/views/Settings.vue#L220) in the UI that handles remote Peer connection, but that would have to change. We want the remote peer connection to be handled by the UI as a parameterized URL that can be triggered from a text message. It can look something like:
https://ui.ambianic.ai/remotePeerConnect?remotePeerId=xyz123

The host name part of the URL should match the host name of the sending user's UI app. For most users that would be https://ui.ambianic.ai, but if someone is doing a dev, test or private install of the Ambianic UI, we should allow that.

When the sending user is generating the link from their in-app Share Connection page, it can populate the full URL using its host name and adding as a parameter the PeerId of the edge devices that will be shared with the requesting user. 

I think for now we should implement sharing button on the sender side per edge device. If the sender manages multiple devices, they can share connection to each, one at a time. In the future if there is user interest we may look at allowing the sender to share connection to multiple devices at once.

@BKristenssonAlfsson any thoughts here?

![Screen Shot 2020-12-29 at 5 11 17 PM](https://user-images.githubusercontent.com/2234901/103319886-04bb4c00-49f9-11eb-88b1-d7a899d23138.png)

**Comment by vickywane** [comment]
Ok. 

Following the sketch, it shows that a user comes back to the installation-flow to continue it after clicking the received URL ( share link ). However from what you are explaining, I guess the installation should end at the point where the access link is shared reason being that there is no way to resume back from where the installation was stopped.

**Comment by ivelin** [comment]
> Ok.
> 
> Following the sketch, it shows that a user comes back to the installation-flow to continue it after clicking the received URL ( share link ). However, from what you are explaining, I guess the installation should end at the point where the access link is shared reason being that there is no way to resume back from where the installation was stopped.
> 
> @ivelin

It is not clear which diagram you are referring to and which steps. Here is an [updated version of the UI flow mockup](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&page-id=igIhIKNUZmc0qu4BMqyh&title=Ambianic%20Install%20UI%20Flow.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1jeuQgz6-dh8erp-kKgldH0dSJAvOMBwN%26export%3Ddownload) with numbered steps. Hopefully we can converge faster by referencing specific step labels.

I guess you may be referring to the transitions (5R6) -> (6). If that is correct then I believe the diagram is self explanatory. After connecting a device successfully, the user should be directed to the timeline page and the install sequence ends. The diagram does not detail the specifics of error handling and recovery during the install process.

**Comment by vickywane** [comment]
Yes, I am making reference to 5R6 -> 6. 

What I assume would happen is this;
A user would click on the sent access link -> This would most likely open a new browser window and they thus lose track of this installation flow.

On a second look at this, I guess there would have to be a background job that keeps checking if the new device has been connected so it moves to (6) after a successful connection. Is this correct @ivelin ?

**Comment by ivelin** [comment]
Yes, all correct. The diagram does not detail everything but you do get the gist of it. Let’s start somewhere and iterate to polish the install UX. Please remember to keep PRs scoped down for smooth and quick review and merge.

**Comment by vickywane** [comment]
Yes, i would reduce the scope of this PR. I found it difficult to work with the current setup, eslint keep throwing errors instead of warnings and this was quite frustrating to work with. I probably would raise issues with regards to this when this PR is completed.

**Comment by ivelin** [comment]
> Yes, I am making reference to 5R6 -> 6.
> 
> What I assume would happen is this;
> A user would click on the sent access link -> This would most likely open a new browser window and they thus lose track of this installation flow.
> 
> On a second look at this, I guess there would have to be a background job that keeps checking if the new device has been connected so it moves to (6) after a successful connection. Is this correct @ivelin ?

Absolutely correct!

**Comment by ivelin** [comment]
related to https://github.com/ambianic/ambianic-ui/discussions/467
