### ISSUE TITLE
Zero-config WiFi setup for Ambianic Edge device

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#397]
Awesome projects like Berrylan (http://www.berrylan.org/) allow edge devices to be easily onboarded to a local Wifi network. 

The issue we need to resolve is how to make that possible within the UI. 

The wifi onboarding sequence requires Bluetooth pairing which is used as a channel to send the Wifi credentials to the edge device.

PWA currently does not support Bluetooth, although it is a Draft W3C API proposal.

Related to ambianic/ambianic-edge/issues/185

**Comment by ivelin** [comment]
It looks like Bluetooth support in PWA is gradually becoming available in mainstream browsers:
https://www.hackster.io/patricia2/offline-pwa-with-bluetooth-le-capabilities-77cbba
https://kaspars.net/blog/sensor-pilot-web-bluetooth
https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API

**Comment by BKristenssonAlfsson** [comment]
Alright. I'll investigate and will do some tries on this.

**Comment by ivelin** [comment]
UX flow diagram below as designed by @BKristenssonAlfsson :

![Screen Shot 2020-07-16 at 4 16 26 PM](https://user-images.githubusercontent.com/2234901/87723803-f4cbea80-c77f-11ea-93b6-c5f88dc084e0.png)

Diagram source [here](https://app.diagrams.net/?page-id=JeqvnSdYqNkFqiVdc35T&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&hide-pages=1#G1Ps-TKQ_WdXS-L6qDeyXqmli9S97mnkFk).

**Comment by ivelin** [comment]
Recent resources related to Vue, PWA and BLE:
* https://www.npmjs.com/package/web-bluetooth-vuex
* https://medium.com/@urish/start-building-with-web-bluetooth-and-progressive-web-apps-6534835959a6
* https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md
* https://dev.to/gerybbg/web-bluetooth-by-example-46dh

**Comment by ivelin** [comment]
@muka this is the UI side of the Wifi auto-config issue you are working on with @BKristenssonAlfsson 
ambianic/ambianic-edge/issues/185

**Comment by ivelin** [comment]
Balena's [Wifi Connect](https://github.com/balena-io/wifi-connect) project looks promising.
It is used by popular projects such as [Home Bridge](https://github.com/homebridge/homebridge-raspbian-image) and [Open Agriculture](https://github.com/OpenAgricultureFoundation/python-wifi-connect).

**Comment by ivelin** [comment]
Done! Closed by https://github.com/ambianic/ambianic-rpi-image/pull/3
