### ISSUE TITLE
TimeLine does not put the latest observation at the top of the list in the PWA when first used.

### ISSUE THREAD

**Issue by jjsenay** [ambianic/ambianic-ui#465]
All,

I went and started a brand new installation with :
https://github.com/ambianic/ambianic-rpi-image/releases/latest/download/image_ambianic_edge-rpi.zip
Installed OK.
When the timeline is started for the first time and observations are made/requested to show the latest timeline you have to scroll **DOWN** the PWA to see them.  he behavior should be the latest timeline event should be at the top of the PWA, no scrolling down.

I start at 7:43 PM, get a timeline, get another timeline at 8:06 PM and it shows up underneath the 7:43 PM event.  THen wait and get another timeline update at 8:15 PM and this timeline shows up under the 8:06PM timeline which is underneath the 7:43 PM timeline.

I get a new timeline at 8:20 PM and it is placed at the **TOP** of the timeline where it is supposed to be.  All the following timeline events are placed on **TOP** of the timeline in proper order.

Ivelin notice this behavior on his installation also.

**Comment by ivelin** [comment]
I observed this too. Looks like the first few events show from oldest to newest and then after that they show as expected from newest to oldest.

**Comment by ivelin** [comment]
This issue may end up being an edge API bug and not related to the UI. Needs investigation.
