### ISSUE TITLE
Email notification settings

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#489]
**Is your feature request related to a problem? Please describe.**
Currently notification settings have to be provided in the edge device config.yaml. 

**Describe the solution you'd like**
End users need a easy way to configure notification preferences via the UI app.

**Describe alternatives you've considered**
Using config.yaml is OK for developers, but not end users.

**Additional context**
The UI has to offer a way for users to provide email address where edge notifications will be sent to.
Respectively the UI needs to update the edge configuration via its config REST API when user's preferences change.

The UI notification settings design would ideally take into account future improvements that allow multiple notification targets - iftt, push notifications, SMS , etc.

**Comment by ivelin** [comment]
@vickywane this is the corresponding backend implementation running on edge deployments: https://github.com/ambianic/ambianic-edge/issues/50

**Comment by ivelin** [comment]
The case was made for supporting multiple email addresses for notification alerts. 

1. Maybe you do not want the your granddad's neighbor to have access to the Edge, but when something bad happens the neighbor can go next door to your granddad's when you live 1000 kilometers away.
2. There is also the idea of peer support. Friends of similar age keep an eye on each other. They can’t physically run to the rescue but they can look at the alert, make an educated decisions and call emergency if needed.
3. And then there is the typical case that a caregiver on duty and a family member should be notified immediately.

**Comment by ivelin** [comment]
@vickywane as you are exploring implementation options for email notifications, there is another possibility to consider.

We could potentially use the recently introduced github sponsors API to obtain an OAuth token from the PWA. Then if the user is a sponsor, we can use that token in the edge to call into a new ephemeral serverless function, let's call it AmbianicNotificationsProxy, which proxies notification calls from the edge to notification service providers such as mailgun, ifttt, AWS SMS, etc. AmbianicNotificationsProxy can verify calls against valid ambiniac github sponsor tokens and then use deployment environment secret variables to route messages from the edge to mailgun and other notification services in the future. It won't need a database to store any data of its own.

I just tested the new github sponsors GraphQL and it seems to work fine. See links and screenshots.

- [API docs](https://docs.github.com/en/graphql)
- [API explorer](https://docs.github.com/en/graphql/overview/explorer)

![Screen Shot 2021-02-02 at 9 15 36 PM](https://user-images.githubusercontent.com/2234901/106693843-e965d280-659c-11eb-8f9a-e86535f061a4.png)

![Screen Shot 2021-02-02 at 9 26 39 PM](https://user-images.githubusercontent.com/2234901/106694105-7b6ddb00-659d-11eb-95bb-25933a23a3fb.png)

This will mean that only sponsoring users can use the new notifications feature, but I think that's a reasonable value for a few dollars per month.

Users who don't want to be sponsoring us, can still use notifications by editing config.yaml on the edge with the service provider credentials of their choice.

Thoughts?

**Comment by vickywane** [comment]
Are all Ambianic users Github sponsors?

**Comment by ivelin** [comment]
> Are all Ambianic users Github sponsors?

No.

**Comment by ivelin** [comment]
Addressed via #773
