### ISSUE TITLE
Improve home screen UX for returning users

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#495]
**Is your feature request related to a problem? Please describe.**
Currently returning users open the app and see a welcome screen that does not provide much value. See screenshot.
![Screen Shot 2021-01-27 at 1 53 30 PM](https://user-images.githubusercontent.com/2234901/106045915-35011380-60a7-11eb-8563-9782cc620ef2.png)

**Describe the solution you'd like**
This screen should not be there at all if there is nothing for the user to gain from it. Most leading apps with a timeline (twitter, fb, instagram) take the user straight to the latest content updates. No friction in between. Straight to added value.

The only exception that warrants a home screen for returning users is if there is something important that they need to learn about the app. A major new feature or a security alert of high urgency.

**Comment by vickywane** [comment]
@ivelin A PR to fix this has been submitted
