### ISSUE TITLE
Add method to filter out detections for People, Objects to reduce timeline noise

### ISSUE THREAD

**Issue by mchapman67** [ambianic/ambianic-ui#497]
**Is your feature request related to a problem? Please describe.**
It would be useful to have the ability in the UX to filter out person and object detection
**Describe the solution you'd like**
Implementation of a button to deactivate Person and Object detection to prevent the output to the timeline

This feature request is to “hide” the output, not to interfere with the AI data gathering.

**Comment by ivelin** [comment]
The immediate solution is to remove object and people detections from the default pipeline setup in config.yaml. Done.

Users can add them back or mix and match via confgi.yaml on the edge device.

In the future we can discuss pipeline config in the UI.
