### ISSUE TITLE
Add UI Stick Figure privacy mode                                                

### ISSUE THREAD

**Issue by mchapman67** [ambianic/ambianic-ui#596]
Ambianic currently provides images to the timeline when an event (such as a fall, person, or object) is detected. Given the privacy focus of Ambianic, it would be beneficial to provide the end-user the ability to switch on the "Stick Figure" mode to enable this feature.

**Comment by ivelin** [comment]
Makes sense.

Related to https://github.com/ambianic/ambianic-ui/issues/565
