### ISSUE TITLE
UI controls for edge pipeline selection

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#642]
**Is your feature request related to a problem? Please describe.**
Currently users have no way of controlling in the UI what pipelines run on the edge device.

Some users prefer to run Object Detection, other prefer Fall Detection, and sometimes they want a combination of Object, Face and Fall detection.

It is possible to setup a variety of pipeline configurations on the edge device via config.yaml, but that is not a user friendly method for users who are not familiar with ssh and yaml format.

**Describe the solution you'd like**
It is desirable to allow user to pick from a list of pipeline templates available in an edge device's default config.yaml file. Since each device may have different hardware and software resources , it is better for the developer of a device profile to prepare a default config.yaml and prepare pipeline templates that would work well for the specific target device. 

Then allow users to see and select one of the templates via the UX. 

**Describe alternatives you've considered**
In the future, it may be also desirable for end users to pick more than one active pipeline template to run at the same time. Provided that the underlying device architecture has sufficient resources to execute multiple pipelines simultaneously.

We could also consider allowing users to compose pipelines from source, AI and other lower level building blocks. That would require more detailed specification of building block interfaces and compatibility to allow smooth lego-like plug-and-play composition. Currently not all blocks are readily compatible with each other in any order.

**Additional context**
Allowing users to see multiple pipeline templates and pick on that should execute requires some changes in the config.yaml format. We may need to introduce a new element such as `run:` that explicitly states which (if any) pipelines should run.

For example the following syntax:
```
...
pipelines:
  - pipeline1:
    - source: ...
    - ai: ...

  - pipeline2:
    - source...

  - pipeline3:
    - source...

run:
  - pipeline1
  - pipeline2
```
would indicate that we want the edge device to execute pipeline1 and pipeline2 in its runtime but not pipeline3.

For backwards compatibility, we may want all declared pipelines to execute when there is no `run:` section.

**Comment by vickywane** [comment]
@ivelin I want to take this up.

**Comment by ivelin** [comment]
Sounds good. Let's start with a design document.

**Comment by ivelin** [comment]
@vickywane good first design draft. See comments and let's iterate.
https://drive.google.com/file/d/12Aeni4Fut9mhGvSuwe03QA2vix5845hI/view
