### ISSUE TITLE
Navbar icons mis-aligned on large resolutions

### ISSUE THREAD

**Issue by vickywane** [ambianic/ambianic-ui#676]
**Describe the bug**
Since the last redesign and removal of icons within the PWA navbar, the remaining icons have become misaligned. They should float to the right of the page. 

**Note:** As shown in the attached screenshot, this bug seems to be unnoticeable on smaller resolutions such as mobile devices.

**To Reproduce**
1. Open the [Ambianic PWA](https://ui.ambianic.ai/timeline) page online on a large resolution device such as a desktop or laptop

**Expected behavior**
The three icons should float to the right of the page

**Screenshots**
![ambianic_navbar_style](https://user-images.githubusercontent.com/29664439/126311090-a82f94e4-ac46-435c-aac1-9b0a40943b62.png)

![ambianic-bug-mobile](https://user-images.githubusercontent.com/29664439/126311492-642e2d8e-983e-46b7-93d9-6c700bf1ee17.png)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - OS: Linux Manjaro
 - Browser: Firefox responsive device emulator.

**Comment by ivelin** [comment]
@vickywane I can confirm this UX bug on my laptop. The navbar icons should be aligned to the right but instead they appear near the center of the screen.

**Comment by vickywane** [comment]
Closing this issue as it was resolved via #677
