### ISSUE TITLE
Color code events in timeline based on priority

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#687]
**Is your feature request related to a problem? Please describe.**
Currently all events show with blue / INFO color in timeline. Whether a person was detected or a fall was detected, the color coding of the circular event icon in the upper left corner is the same. See screenshot.

Ability to filter events based on priority would be also helpful for notifications.

**Describe the solution you'd like**
It would be desirable to color code event icons based on priority values: INFO, WARNING so its easier for users to spot more important events faster.

[See example JSON payloads of events](https://github.com/ambianic/ambianic-ui/issues/565#issuecomment-806020720) sent from an edge device. Notice the priority parameter.
```
- args:
    datetime: '2021-03-24T05:15:57.722352'
    id: 5906a1d5bdc14a1daadd2555b39bd0f3
    image_file_name: 20210324-051557.722352-image.jpg
    inference_meta:
      display: Object Detection
    inference_result:
     ...
  priority: INFO
```

The PWA code is already designed to color code icons based on event priority level (see this). 

However the edge device code always logs events at info level ([see this](https://github.com/ambianic/ambianic-edge/blob/d72e12000b3e98665c119ae4d2b5cd7a983a5ee2/src/ambianic/pipeline/store.py#L117)).
The event level is then picked up by the event formatter and saved in the timeline event yaml log file ([see this](https://github.com/ambianic/ambianic-edge/blob/440cebc2b53da25d7cbb07c873bc1cf603010640/src/ambianic/pipeline/timeline.py#L100)).

As an initial step, we can add a `priority` argument to the edge pipeline configuration yaml, that sets the default priority level for each type of detection event. For example:

```
     - detect_falls: # look for falls
        ai_model: fall_detection
        confidence_threshold: 0.6
        priority : WARNING    # default priority of the event, one of: INFO, WARNING or CRITICAL
```

Then the event logger in `store.py` can save each event at the configured priority / log level, which should result in the correct color coding in the UI.

Here is the [corresponding ambianic-edge issue](https://github.com/ambianic/ambianic-edge/issues/363).

**Describe alternatives you've considered**
A more advanced version of this feature would allow users to edit the default priority level for various types of events. For example for certain scenarios person detection maybe just at INFO level (counting people appearances in a living room), but in others it may be a WARNING priority (people breaching of a security perimeter at night).

**Additional context**
Yet another feature to consider is the ability to mute events under a certain priority threshold. For example a user may only want to be notified about WARNING level events and not INFO events.

![Screen Shot 2021-08-06 at 7 30 52 AM](https://user-images.githubusercontent.com/2234901/128510739-ba62327c-fa90-4085-8900-cf16d51238b8.png)

**Comment by vickywane** [comment]
@ivelin I will take this up and submit a PR when implemented.

**Comment by vickywane** [comment]
> The PWA code is already designed to color code icons based on event priority level (see this).

@ivelin There's a missing link here

**Comment by vickywane** [comment]
@ivelin I'm going through this gradually, and a fix for this feature request still seems unclear to me. 

>As an initial step, we can add a priority argument to the edge pipeline configuration yaml, that sets the default priority level for >each type of detection event. For example:
>
> ```yaml
>     - detect_falls: # look for falls
>        ai_model: fall_detection
>        confidence_threshold: 0.6
>        priority : WARNING    # default priority of the event, one of: INFO, WARNING or CRITICAL
> ```

If this will be a fix to this issue, then this issue should have been opened in the [edge repository](https://github.com/ambianic/ambianic-edge).

On the second hand, should the priority level be sent to the edge-device from the PWA?

**Comment by ivelin** [comment]
> > The PWA code is already designed to color code icons based on event priority level (see this).
> 
> @ivelin There's a missing link here

https://github.com/ambianic/ambianic-ui/blob/1c96143711714e8f05f04fc7222f1bb5823325b3/src/views/Timeline.vue#L396

**Comment by ivelin** [comment]
Yes, this will involve updates on both edge and UI. We need a separate `ambianic-edge` issue that links to this one.

As an initial step, we can add the suggested `config.yaml` attribute on the edge. That will enable reasonable default behavior. When implemented , we still need a thorough test coverage on the UI side to ensure edge events with different priorities are processed and displayed correctly.

We can create a follow-up issues that allows users to do several things via the UI:
- Set a system wide or edge-device-scoped minimum event priority level above which edge devices should fire events. Respectively edge devices will be expected to ignore firing events below a certain level. This needs to be though through. Maybe one threshold for real-time notifications and another threshold for logging events in the timeline history so users can still search for lower level events if they want to only get notified on higher priority events.
- Assign event priority per type of detection event. This will update the config attributes on the edge device. For some users and situations, it may be more important to detect falls, while for others it may be more important to detect person identifies.

Thoughts?

> @ivelin I'm going through this gradually, and a fix for this feature request still seems unclear to me.
> 
> > As an initial step, we can add a priority argument to the edge pipeline configuration yaml, that sets the default priority level for >each type of detection event. For example:
> > ```yaml
> >     - detect_falls: # look for falls
> >        ai_model: fall_detection
> >        confidence_threshold: 0.6
> >        priority : WARNING    # default priority of the event, one of: INFO, WARNING or CRITICAL
> > ```
> 
> If this will be a fix to this issue, then this issue should have been opened in the [edge repository](https://github.com/ambianic/ambianic-edge).
> 
> On the second hand, should the priority level be sent to the edge-device from the PWA?

**Comment by vickywane** [comment]
> Thoughts?

I am resuming work on this. 
I will break the issue down into smaller chunks. I have started off with the first part on the Ambianic Edge in this [pull request](https://github.com/ambianic/ambianic-edge/pull/391).

**Comment by ivelin** [comment]
Breaking it down into smaller PRs is fine, but each has to add a meaningful improvement that is well tested. Tests should demonstrate clearly how the change is expected to work and be used by other upcoming PRs.
