### ISSUE TITLE
[FEATURE] Performance improvement: cache timeline events in browser local indexdb

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#706]
**Is your feature request related to a problem? Please describe.**
Currently the UI fetches timeline events from an edge device each time the PWA starts or an Edge Device connection is (re)connected to the UI. This leads to a sluggish user experience if the user wants to close the app and check the timeline in a few minutes or hours.

**Describe the solution you'd like**
With modern browsers, we should be able to cache locally a time indexed log of events per edge device and show them quickly to the user when requested. The UI should still try to pull the latest events in the background but in the meanwhile the user can look and act on previously cached events.

We can use an automatic retention policy for cached timeline event data. For example auto delete oldest data when the PWA reaches 70% of its cache quota on the local browser.

Note that we have to be careful and merge newly arrived events from the API correctly into cache before rendering. Potential duplicate events from the API that were already cached, should be ignored.

**Additional context**
Many smart cameras store user data in the cloud, which makes it easier and faster to retrieve user data from a mobile app on demand. However that increases the risk of intentional or unintentional privacy violation.

_Notes on local browser db API:_
Indexeddb appears to be the latest widely supported web3c standard. It introduces indexing and SQL like search capabilities.
Indexeddb is considered a low level framework. Of the existing high level local db frameworks, it appears that [Dexie](https://github.com/dfahlander/Dexie.js) best fits our intended use as it focuses on indexed data query over temporal and multi key data.

Other popular frameworks like localforge and store.js are focused on simple key/value pair lookups and do not focus on structured data query. Although there are extensions to these frameworks that provide query capabilities.

**Comment by vickywane** [comment]
This is still valid issue. 

Since the last release introduced [Dexie](https://dexie.org/) on a large scale, I’ll likely be working on this next week.

**Comment by ivelin** [comment]
To answer your questions:
> Should the cached object detection be shown ONLY when the PWA is offline i.e not connected to a device?

No, I think cached issue can be shown at any time the user opens the timeline page for a particular selected device. When there is a connection available to that edge device, the UI should pull and merge latest incoming data with the cached data.

> Should the cached object detection be shown IN-THE-PROCESS of fetching new object detections from connected Ambianic Edge?

Yes, I think so. The user can review previously pulled events while waiting on the new ones to show up in the timeline.
