### ISSUE TITLE
UI.PWA cannot connect with the Edge.  

### ISSUE THREAD

**Issue by jjsenay** [ambianic/ambianic-ui#730]
Been working the Edge with a new camera with IR.  Plugged the Pi in.  
Been starting and stopping the local Edge.

I cannot connect with the Edge via Local or via remote.   See the Console Log files.

I just ssh into the Edge and did an ambianic logs command.  Says there is a bad certificate.
[ambianic_edge_logs.txt](https://github.com/ambianic/ambianic-ui/files/7231831/ambianic_edge_logs.txt)
 
![Screen Shot 2021-09-26 at 12 03 34 PM](https://user-images.githubusercontent.com/8701163/134817471-ab3e93ce-42c0-43f0-9464-ad6590e8e38d.png)
![Screen Shot 2021-09-26 at 11 57 40 AM](https://user-images.githubusercontent.com/8701163/134817473-371b7944-9dbc-4e14-8da2-c83f848ab671.png)
![Screen Shot 2021-09-26 at 11 56 47 AM](https://user-images.githubusercontent.com/8701163/134817475-ed1cc539-ecd6-45b5-a450-2e32f9d9492f.png)
[ui.ambianic.ai-_only_tab_open.log](https://github.com/ambianic/ambianic-ui/files/7231832/ui.ambianic.ai-_only_tab_open.log)
[ui.ambianic.ai-1632675387197.log](https://github.com/ambianic/ambianic-ui/files/7231833/ui.ambianic.ai-1632675387197.log)

**Comment by ivelin** [comment]
Got it. Have you tried with any other browser than Brave?

**Comment by jjsenay** [comment]
Worked with Safari today and had similar results.  Did not work local, But would work with Remote Edge.
Ifconfig:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 82:0a:59:3d:8d:80 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 88:1f:a1:1d:eb:3a 
	inet6 fe80::80b:e55e:37b3:f89b%en1 prefixlen 64 secured scopeid 0x5 
	inet 192.168.1.4 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	options=400<CHANNEL_IO>
	ether 0a:1f:a1:1d:eb:3a 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 3e:8b:b8:85:1d:f1 
	inet6 fe80::3c8b:b8ff:fe85:1df1%awdl0 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=50b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV,CHANNEL_IO>
	ether 10:dd:b1:d7:40:1f 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (none)
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:0a:59:3d:8d:80 
	media: autoselect <full-duplex>
	status: inactive
fw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 4078
	lladdr 44:fb:42:ff:fe:64:f6:36 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect <full-duplex>
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::bcee:d9ee:f438:b6ea%utun0 prefixlen 64 scopeid 0xb 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::7048:49e6:348c:525c%utun1 prefixlen 64 scopeid 0xc 
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1420
	inet 10.8.191.152 --> 10.8.191.152 netmask 0xffffffff 

I am running through a VPN
[Console_MAC_Safari_Local.txt](https://github.com/ambianic/ambianic-ui/files/7238493/Console_MAC_Safari_Local.txt)
[Console_MAC_Safari_Remote_worked.txt](https://github.com/ambianic/ambianic-ui/files/7238495/Console_MAC_Safari_Remote_worked.txt)
[MAC_SAFARI_Local_JSCONSOLE.txt](https://github.com/ambianic/ambianic-ui/files/7238496/MAC_SAFARI_Local_JSCONSOLE.txt)

**Comment by jjsenay** [comment]
On Safari, when I use connect to Remote Edge and then switch to connect with Local Edge, it works.  I am connecting to the Local Edge Device.  Attached JS Console logs.  The first few lines maybe from the Remote instance.  Just cannot switch over fast enough to Loca
[MAC_Console_Safari_Remote First_then_Local.txt](https://github.com/ambianic/ambianic-ui/files/7238579/MAC_Console_Safari_Remote.First_then_Local.txt)
l.

**Comment by ivelin** [comment]
Interesting. Some sort of p2p state machine corruption. Can you record a
video with the steps you take to make it brake? From a clean start. Include
the UI next to browser dev console in the video recording.

**Comment by jjsenay** [comment]
Ivelin,

I got to do some more research.  Swimming laps in the pool today I realized that I never started the PWA as an app.  Just went with ui.ambianic.ai

Let me see how it behaves from the installed PWA.

Yes I will do screen record and put it on Google Drive and share the link(s)


JJS

**Comment by ivelin** [comment]
Nice. Swimming is good for meditation.

Good thought. It should not make a difference from UX POV how you start the
app. Both should work fine. If you see difference in behavior it’s probably
a bug.
