### ISSUE TITLE
UI not showing time line, it is just "pong" mode

### ISSUE THREAD

**Issue by jjsenay** [ambianic/ambianic-ui#741]
MAC/OS
Brave Browser
Remote Edge

I can start up the UI in the "remote" mode fine.  I can pull a timeline.  Shows up in the JSConsole.

Then after 5 minutes it goes into a :
PeerJS:  DC#dc_k81l618i3bj dc onmessage: {"status": 200}   vendors~c6d67eea.93d64e6d.js?__WB_REVISION__=0e68e3506ddd1e80d06b:1 PeerJS

It just loops.

I can see in the Ambianic Log files that the Edge is seeing me walk around, and taking timeline samples, but the latest frames do not show up in the time line in the UI
[Edge_See_UI_Just_Pings.txt](https://github.com/ambianic/ambianic-ui/files/7268148/Edge_See_UI_Just_Pings.txt)
[JS_Console_edge_JustPings.txt](https://github.com/ambianic/ambianic-ui/files/7268149/JS_Console_edge_JustPings.txt)

Then I get an Array buffer error, see attached file
[JSConsole_Array_Buffer_problem.txt](https://github.com/ambianic/ambianic-ui/files/7268215/JSConsole_Array_Buffer_problem.txt)

**Comment by ivelin** [comment]
@jjsenay is this still a problem? If so, can you share a screen recording with the dev console open that shows how you get to this issue.
