### ISSUE TITLE
[FEATURE] Introduce VueX namespace to avoid name collisions within modules

### ISSUE THREAD

**Issue by vickywane** [ambianic/ambianic-ui#755]
**Is your feature request related to a problem? Please describe.**
We are working towards making sure that state management within the PWA has a modular structure and this has led us to create independent VueX modules for the PWA pages. However, as the number of modules increase, we are bound to have name collisions within the modules.    

**Describe the solution you'd like**
The use of [namespaces](https://vuex.vuejs.org/guide/modules.html#module-local-state) is recommended when avoiding name collisions within VueX modules. Hence, this should also be employed within the PWA.  

**Describe alternatives you've considered**
Prefixing the constants used within the modules has also been considered, however it seems to be a short term solution.

**Comment by ivelin** [comment]
Done.
