### ISSUE TITLE
Home Router resets IP address of Edge.  UWA losses connection 

### ISSUE THREAD

**Issue by jjsenay** [ambianic/ambianic-ui#759]
I could connect to the Edge this morning using the beta UI-PWA .  Went out and did some shopping, came back and I could not get to the timeline.  

I tried to reconnect via the beta UI-PWA but there was not a **clear** way to do it.  

I then tried to ssh into the Edge and I could not.  I tried to ping the Edge, but I could not.  Opened up my router admin page and saw the Edge was giving a new IP address.

My home router, every month ( I think ) reassigns a new IP address.  The beta PWA-UI losses connection to the EDGE.
I have to reload the beta PWA-UI and since I am on a VPN I use connect to remote option and I connect to the Edge Timeline.

How to fix?  On the home router assign an IP address to each EDGE.  Do not let the DHCP server regroom/reset the IP address of the Edge.

**Comment by vickywane** [comment]
@jjsenay I’m waiting for your recording to take a look at this.

**Comment by ivelin** [comment]
Is this still an issue?
