### ISSUE TITLE
Setup Google Lighthouse PWA test tool in CI

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-ui#87]
https://github.com/GoogleChrome/lighthouse-ci

**Comment by ivelin** [comment]
Occasionally UI code changes break the PWA certification and the app is not installable or some other issues pops up.

At this time Google has made available Lighthouse in a docker container for CI use. We need to take advantage of it to ensure continuous PWA compliance.

**Comment by ivelin** [comment]
Some relevant resources to consider:

A couple of maintained Github Actions for Lighthouse:
1. 
https://github.com/marketplace/actions/lighthouse-ci-action
How To use it blog post: 
https://www.jacobtomlinson.co.uk/posts/2020/testing-static-sites-with-lighthouse-ci-and-github-actions/

2. Fewer contributors but also recently updated:
https://github.com/marketplace/actions/lighthouse-check

There is also an instructional blog how to include Lighthouse directly into a Github Action low without a Github Action:
https://dev.to/jakepartusch/the-best-way-to-automate-performance-checks-in-github-584e

**Comment by sniperadmin** [comment]
amazing @ivelin!

thanks alot, this will save much time!

**Comment by ivelin** [comment]
Closed by #348
